from enum import Enum


class ActivityCategoryType(str, Enum):
    # DIRECT
    STATIONARY_COMBUSTION = "STATIONARY_COMBUSTION"
    MOBILE_COMBUSTION = "MOBILE_COMBUSTION"
    PROCESS_EMISSIONS = "PROCESS_EMISSIONS"
    FUGITIVE_EMISSIONS = "FUGITIVE_EMISSIONS"

    # ELECTRICITY
    PURCHASED_ELECTRICITY = "PURCHASED_ELECTRICITY"
    PURCHASED_STEAM_HEAT_COOLING = "PURCHASED_STEAM_HEAT_COOLING"

    # UPSTREAM
    PURCHASED_GOODS_AND_SERVICES = "PURCHASED_GOODS_AND_SERVICES"
    CAPITAL_GOODS = "CAPITAL_GOODS"
    FUEL_AND_ENERGY_RELATED_ACTIVITIES = "FUEL_AND_ENERGY_RELATED_ACTIVITIES"
    UPSTREAM_TRANSPORT_AND_DISTRIBUTION = "UPSTREAM_TRANSPORT_AND_DISTRIBUTION"
    WASTE_GENERATED_IN_OPERATIONS = "WASTE_GENERATED_IN_OPERATIONS"
    BUSINESS_TRAVEL = "BUSINESS_TRAVEL"
    EMPLOYEE_COMMUTING = "EMPLOYEE_COMMUTING"
    UPSTREAM_LEASED_ASSETS = "UPSTREAM_LEASED_ASSETS"

    # DOWNSTREAM
    DOWNSTREAM_TRANSPORT_AND_DISTRIBUTION = "DOWNSTREAM_TRANSPORT_AND_DISTRIBUTION"
    PROCESSING_OF_SOLD_PRODUCTS = "PROCESSING_OF_SOLD_PRODUCTS"
    USE_OF_SOLD_PRODUCTS = "USE_OF_SOLD_PRODUCTS"
    END_OF_LIFE_OF_SOLD_PRODUCTS = "END_OF_LIFE_OF_SOLD_PRODUCTS"
    DOWNSTREAM_LEASED_ASSETS = "DOWNSTREAM_LEASED_ASSETS"
    FRANCHISES = "FRANCHISES"
    INVESTMENTS = "INVESTMENTS"

    # OTHERS
    CUSTOM = "CUSTOM"
